In [ ]:
# You are given a map in form of a two-dimensional integer grid where 1 represents land and 0 represents water. Grid cells are connected horizontally/vertically (not diagonally). The grid is completely surrounded by water, and there is exactly one island (i.e., one or more connected land cells). The island doesn't have "lakes" (water inside that isn't connected to the water around the island). One cell is a square with side length 1. The grid is rectangular, width and height don't exceed 100. Determine the perimeter of the island.

# Example:

# [[0,1,0,0],
#  [1,1,1,0],
#  [0,1,0,0],
#  [1,1,0,0]]

# Answer: 16
# Explanation: The perimeter is the 16 yellow stripes in the image below:


In [ ]:
def islandPerimeter(self,grid):
    array = grid[0,]
    count = 0
    for i_1 in range(len(grid)):
        for i_2 in range(len(array)):
            if grid[i_1,i_2]==1:
                sum(grid[i_1])
                
            
    

In [2]:
import numpy as np

In [9]:
a = np.array([[1,32,54],[34,6,56],[234,765,23],[54,32,65]])

In [10]:
a

array([[  1,  32,  54],
       [ 34,   6,  56],
       [234, 765,  23],
       [ 54,  32,  65]])

In [11]:
l=[]
for i in a:
    l.append(i)
print(l)

[array([ 1, 32, 54]), array([34,  6, 56]), array([234, 765,  23]), array([54, 32, 65])]


In [12]:
len(a)

4

In [15]:
len(a[0,])

3

In [16]:
a = np.array([[1,0,0,1,0,1],[0,1,1,0,1,0],[1,1,0,0,0,0]])

In [26]:
a

array([[1, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 1, 0],
       [1, 1, 0, 0, 0, 0]])

In [21]:

sum(a[2,]==1)

2

In [29]:
def f(x):
    return x*x
b=[32,24,42,565,23]

In [33]:
list(map(f,a))

[array([1, 0, 0, 1, 0, 1]),
 array([0, 1, 1, 0, 1, 0]),
 array([1, 1, 0, 0, 0, 0])]

In [38]:
import operator as op

In [39]:

operator.add(1,2)

NameError: name 'operator' is not defined

In [1]:
# solution
def islandPerimeter(self, grid):
    return sum(sum(map(operator.ne, [0] + row, row + [0]))
               for row in grid + map(list, zip(*grid)))